language: ruby
rvm:
- 2.3.3

before_script:
 - chmod +x ./assets/js/cibuild

script: ./assets/js/cibuild

branches:
    only:
        - master

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

sudo: false