title: ManingTech
email: info@dreamdressnoiva.com
description: >- # this means to ignore newlines until "baseurl:"
  Moçambique TechConectado
url: "https://maning.tech"

# Build settings
markdown: kramdown
permalink: pretty

plugins:
  - jekyll-email-protect 
  - jekyll-paginate-v2
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-analytics
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - bower_components

sass:
  sass_dir: assets/_sass
  style: compressed

image: /assets/img/logotipo.jpeg

pagination:
  enabled: true
  per_page: 15
  limit: 0
  sort_field: 'date'
  sort_reverse: true
  trail: 
    before: 2
    after: 2

image:
logo: /assets/img/brand/logotipo.svg
color: "#009688"

jekyll_analytics: 
  GoogleAnalytics:
    id: 
    anonymizeIp: false