# Site settings
title: ManingTech
email: maningtech@outlook.com
description: "Moçambique TechConectado"
url: "http://maningtech.github.io/maningtech"
port: 4040

# Social
facebook: maningtech
twitter: 
    username: maning_tech
github: Maningtech
google: maningtech
logo: assets/img/brand/favicon.svg

#site author
author:
    name: Ivo Zinenda
    email: izinenda@outlook.com
    google: +IvoZinenda
    facebook: zinenda.jerk
    twitter: Imaz_3g
    linkedin: zinendajerk
    github: zinenda
# Build settings
markdown: kramdown

sass:
    sass_dir: assets/_sass
    style: compressed

  
image: /assets/img/brand/logotipo.png

gems:
  - jekyll-seo-tag
  - jekyll-sitemap