# Site settings
title: ManingTech
email: maningtech@outlook.com
description: "Moçambique TechConectado"
url: ""
port: 4040

# Social
facebook: maningtech
twitter: 
    username: maning_tech
github:
    url: "http://maningtech.github.io"
    username: maningtech
google: maningtech
logo: assets/img/brand/favicon.svg

image: /assets/img/brand/logotipo.svg

#site author
author:
    name: Ivo Zinenda
    email: izinenda@outlook.com
    google: +IvoZinenda
    facebook: zinenda.jerk
    twitter: Imaz_3g
    linkedin: zinendajerk
    github: zinenda
# Build settings
markdown: kramdown
humanize:
    date_format: "%d/%m/%Y"

jekyll_timeago:
  depth: 3
  today: 'hoje'
  yesterday: 'ontem'
  tomorrow: 'amanha'
  and: 'e'
  suffix: 'atras'
  prefix: ''
  suffix_future: ''
  prefix_future: 'em'
  years: 'anos'
  year: 'ano'
  months: 'meses'
  month: 'mes'
  weeks: 'semanas'
  week: 'semana'
  days: 'dias'
  day: 'dia'

sass:
    sass_dir: assets/_sass
    style: compressed


gems:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate