# Jekyll Config file

title: ManingTech
description: Moçambique TechConectado
email: info@izitag.site
image: /assets/img/brand/logotipo.svg

twitter:
    username: maning_tech
facebook:
    app_id: 1034422419934923
    publisher: maningtech
    admins: maningtech
logo: /assets/img/brand/logotipo.svg
social:
    name: maningtech
    links:
google_analytics_code: UA-73721868-1 # replace with the your analytics code

author: Ivo Zinenda

# Build Settings
markdown: kramdown
paginate: 8
paginate_path: /page:num/
permalink: pretty

plugins: 
    - jekyll-sitemap
    - jekyll-seo-tag
    - jekyll-paginate
    - jekyll-feed

# Assets
sass:
    sass_dir: assets/_sass
    style: compressed

exclude:
    - vendor
    - Gemfile
    - Gemfile.lock
    - README.md
    - LICENSE
    - CNAME
    - bower_components

compress_html:
  clippings: all
  endings: all
comments: ["<!--", "-->"]