# Jekyll Config file

title: ManingTech
description: Moçambique TechConectado
email: maningtech@outlook.com
image: /assets/img/brand/logotipo.jpg
url: ""

twitter:
    username: maning_tech
facebook:
    app_id: 1034422419934923
    publisher: maningtech
    admins: maningtech
logo: /assets/img/brand/logo.png
social:
    name: maningtech
    links:
google_analytics_code: UA-73721868-1 # replace with the your analytics code

author: Ivo Zinenda

# Build Settings
markdown: kramdown
paginate: 10
paginate_path: /page:num/


# forestry.io
defaults:
    - scope:
        path:
        type: posts
    values:
        title:
        image: ""
        author: ""
        categories: []
        tags: []
        fontes: ""


gems: 
    - jekyll-admin
    - jekyll-github-metadata
    - jekyll-auto-image
    - jekyll-timeago
    - jekyll-email-protect
    - autolink
    - jekyll-minifier
    - jekyll-sitemap
    - jekyll-seo-tag
    - jekyll-paginate

# Assets
sass:
    sass_dir: assets/_sass
    style: compressed

port: 1234